### ISSUE TITLE
some errors in V0.4.0

### ISSUE THREAD

**Issue by DDZH-DEV** [glushkovds/php-smpp#2]
```
PhpSmpp\Exception\SmppException: Failed to read reply to command: 0x2 in /www/wwwroot/think-workerman/PhpSmpp/Client.php:715
Stack trace:
#0 /www/wwwroot/think-workerman/PhpSmpp/Client.php(625): PhpSmpp\Client->sendCommand(2, 'yishui\x00P3iwnbxK...')
#1 /www/wwwroot/think-workerman/PhpSmpp/Client.php(179): PhpSmpp\Client->bind('***', '***', 2)
#2 /www/wwwroot/think-workerman/PhpSmpp/Service/Sender.php(27): PhpSmpp\Client->bindTransmitter('yishui', 'P3iwnbxK')
#3 /www/wwwroot/think-workerman/PhpSmpp/Service/Service.php(87): PhpSmpp\Service\Sender->bind()
#4 /www/wwwroot/think-workerman/PhpSmpp/Service/Sender.php(53): PhpSmpp\Service\Service->enshureConnection()
#5 /www/wwwroot/think-workerman/sms/client_service/start_send.php(18): PhpSmpp\Service\Sender->send('+86***', '\xE7\x9F\xAD\xE4\xBF\xA1\xE9\xAA\x8C\xE8\xAF\x81\xE7\xA0\x81...', Object(PhpSmpp\Pdu\Part\Address))
#6 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(2393): {closure}(Object(Workerman\Worker))
#7 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(1541): Workerman\Worker->run()
#8 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#9 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#10 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
#11 /www/wwwroot/think-workerman/sms/client_service/linux_server.php(39): Workerman\Worker::runAll()
#12 {main}
```
```
PhpSmpp\Exception\SmppException: Failed to read reply to command: 0x9 in /www/wwwroot/think-workerman/PhpSmpp/Client.php:715
Stack trace:
#0 /www/wwwroot/think-workerman/PhpSmpp/Client.php(625): PhpSmpp\Client->sendCommand(9, '***\x00***...')
#1 /www/wwwroot/think-workerman/PhpSmpp/Client.php(193): PhpSmpp\Client->bind('***', '***', 9)
#2 /www/wwwroot/think-workerman/PhpSmpp/Service/Listener.php(15): PhpSmpp\Client->bindTransceiver('***', '***')
#3 /www/wwwroot/think-workerman/PhpSmpp/Service/Service.php(87): PhpSmpp\Service\Listener->bind()
#4 /www/wwwroot/think-workerman/PhpSmpp/Service/Listener.php(34): PhpSmpp\Service\Service->enshureConnection()
#5 /www/wwwroot/think-workerman/PhpSmpp/Service/Listener.php(27): PhpSmpp\Service\Listener->listenOnce(Object(Closure))
#6 /www/wwwroot/think-workerman/sms/client_service/start_read.php(25): PhpSmpp\Service\Listener->listen(Object(Closure))
#7 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(2393): {closure}(Object(Workerman\Worker))
#8 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(1541): Workerman\Worker->run()
#9 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#10 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#11 /www/wwwroot/think-workerman/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
#12 /www/wwwroot/think-workerman/sms/client_service/linux_server.php(39): Workerman\Worker::runAll()
#13 {main}
```
sender:
![image](https://user-images.githubusercontent.com/11805413/88471586-ac5dbb00-cf3d-11ea-93b7-d2cbf26f8615.png)

read:
![image](https://user-images.githubusercontent.com/11805413/88471591-baabd700-cf3d-11ea-9824-78dc1effd513.png)

**Comment by glushkovds** [comment]
Hi! Thank you for your interest for my library!
Now FakeTransport isn't ready, work in progress, sorry. You should use SocketTransport.

**Comment by glushkovds** [comment]
Hello! Now FakeTransport is ready. Version v0.5.0
